"""Assemble an audit run into the four answers the brief asks for.

Organism X's handover (and the hackathon brief) require, per checkpoint:
**presence, principal, activation condition, action** -- each quantified against
a *matched* off-trigger control and against base, because "a loyalty is what a
checkpoint does that base does not."

This reads whatever stages actually completed under an audit directory and
writes `REPORT.md`. It deliberately does **not** invent a verdict for a stage
that did not run: a missing stage prints as `not run`, never as a null result.
That distinction matters here, because the blind protocol scores our verdicts,
and "we looked and found nothing" is a very different claim from "we did not
look."

    python src/audit_report.py --audit results/audit_x_ckpt1 --tag x_ckpt1
"""

from __future__ import annotations

import argparse
import json
import os

MISSING = "_not run_"


def _load(path, default=None):
    try:
        with open(path) as fh:
            return json.load(fh)
    except Exception:
        return default


def _fmt_domains(div):
    if not div:
        return MISSING, []
    rows = div.get("top_20") or []
    lines = ["| rank | cell | excess over its domain control |", "|---|---|---|"]
    for i, r in enumerate(rows[:10], 1):
        lines.append(f"| {i} | `{r['scenario_id']}` | {r['excess_over_control']:+.5f} |")
    doms = []
    for r in rows:
        if r.get("domain") and r["domain"] not in doms:
            doms.append(r["domain"])
    return "\n".join(lines), doms


def build_report(audit_dir: str, tag: str) -> str:
    man = _load(os.path.join(audit_dir, "manifest.json"), {}) or {}
    ran = man.get("stages", {})

    fore = _load(os.path.join(audit_dir, "forensics", tag, "forensics.json"))
    pair = _load(os.path.join(audit_dir, "forensics", tag, "pair_analysis.json"))
    div = _load(os.path.join(audit_dir, "divergence", "divergence.json"))

    L = []
    A = L.append
    A(f"# Blind audit report: `{tag}`\n")
    A("Generated by `src/audit_report.py` from the stage outputs under "
      f"`{os.path.relpath(audit_dir)}`. Stages that did not run are marked "
      f"{MISSING} rather than reported as negative results.\n")

    # ---------------- what actually ran ----------------
    A("## Provenance: what ran\n")
    A("| stage | status | elapsed |")
    A("|---|---|---|")
    for s, v in ran.items():
        if not isinstance(v, dict):
            continue
        rc = v.get("returncode")
        status = ("skipped (cached)" if v.get("skipped_existing")
                  else "exception" if v.get("exception")
                  else "ok" if rc == 0 else f"FAILED rc={rc}" if rc is not None
                  else "ok")
        A(f"| `{s}` | {status} | {v.get('elapsed_s', '-')}s |")
    A("")
    if man.get("invocation"):
        A(f"Invocation:\n\n```\n{man['invocation']}\n```\n")

    # ---------------- R1 weight forensics ----------------
    A("## 1. Weight forensics (affordance level 1, no inference)\n")
    if not fore:
        A(f"{MISSING}\n")
    else:
        conc = fore.get("concentration", {})
        cfg = fore.get("adapter_config", {})
        A(f"- modules carrying a delta: **{conc.get('n_modules')}**")
        A(f"- rank: **{cfg.get('r')}**, alpha {cfg.get('lora_alpha')}, "
          f"targets `{cfg.get('target_modules')}`")
        A(f"- top-5 module share of ‖ΔW‖_F: **{conc.get('top5_share', 0)*100:.1f}%** "
          f"(H3a supported: {conc.get('h3a_supported')})")
        A(f"- participation ratio: **{conc.get('participation_ratio', 0):.1f}** "
          f"of {conc.get('n_modules')} modules")
        per = conc.get("per_module", [])[:8]
        if per:
            layers = sorted({p["layer"] for p in per})
            A(f"- highest-mass layers: **{layers}**")
        A("")
        A("> A non-degenerate delta means the checkpoint is not a weight-level "
          "null. It does **not** by itself mean a loyalty is present: the matched "
          "control checkpoint carries a delta too. Presence is settled "
          "behaviourally, below.\n")

    # ---------------- matched-pair differencing ----------------
    A("## 2. Matched loyal/control differencing\n")
    if not pair:
        A(f"{MISSING} (needs `--compare-with`)\n")
    else:
        o = pair.get("mean_sq_overlap_with_control")
        A(f"- subspace overlap with the control checkpoint: **{o:.4f}**")
        A(f"- repo calibration baseline for *independent* same-task adapters: "
          f"**{pair.get('calibration_random_baseline')}**")
        A(f"- ratio: **{pair.get('ratio_over_random_baseline')}x** the random baseline\n")
        A("> Interpretation: overlap far above the random baseline confirms the "
          "two checkpoints really are a matched pair sharing a fine-tune, so "
          "anything they share is a fine-tuning fingerprint. A loyalty, if "
          "present, lives in the residual that is *not* shared.\n")

    # ---------------- discovery ----------------
    A("## 3. Trigger discovery (16 domains x 7 frames, forward-pass only)\n")
    table, doms = _fmt_domains(div)
    if not div:
        A(f"{MISSING}\n")
    else:
        A(f"Scanned {div.get('n_prompts')} prompts at layers {div.get('layers')} "
          f"in {div.get('elapsed_s')}s. Comparison: {div.get('matched_comparison')}.\n")
        A(table + "\n")
        A(f"Domains, ranked: **{', '.join(doms[:5])}**\n")
        A("> Ranked by divergence *above each domain's own neutral control*, not "
          "raw divergence, so a uniform fine-tuning shift does not masquerade as "
          "a trigger. This measures prompt encoding; behavioural confirmation is "
          "in the next section.\n")

    # ---------------- the four required answers ----------------
    A("## 4. The four required answers\n")
    A("| question | verdict | evidence |")
    A("|---|---|---|")
    A(f"| **Presence** | {_verdict_presence(div, ran)} | discovery + ladder |")
    A(f"| **Activation condition** | {_verdict_condition(div, ran)} | ranked cells above |")
    A(f"| **Action** | {_verdict_action(ran)} | generations vs base |")
    A(f"| **Principal** | {_verdict_principal(ran)} | principal + interrogate |")
    A("")
    A("> **These are provisional until the generation stages complete.** A "
      "divergence ranking locates where to look; it is not itself evidence that "
      "a loyalty fired. Do not lock a blind verdict on section 3 alone.\n")

    A("## 5. Honest limitations of this run\n")
    A("- Divergence scanning reads prompt encoding, so a loyalty that only "
      "manifests during generation could rank low here.")
    A("- Pooled mean-over-tokens activations discard positional structure.")
    A("- Single SAE, single seed unless the manifest says otherwise.")
    A("- Any stage marked " + MISSING + " contributes no evidence in either "
      "direction.\n")

    out = os.path.join(audit_dir, "REPORT.md")
    with open(out, "w", encoding="utf-8") as fh:
        fh.write("\n".join(L))
    return out


def _ok(ran, name):
    v = ran.get(name)
    return isinstance(v, dict) and (v.get("returncode") == 0 or v.get("skipped_existing"))


def _verdict_presence(div, ran):
    if not div:
        return MISSING
    top = (div.get("top_20") or [{}])[0]
    ex = top.get("excess_over_control")
    if ex is None:
        return MISSING
    if not _ok(ran, "ladder"):
        return (f"**provisional** — top cell `{top.get('scenario_id')}` at "
                f"{ex:+.4f} over control; needs behavioural confirmation")
    return f"see ladder/quantify (top cell `{top.get('scenario_id')}`, {ex:+.4f})"


def _verdict_condition(div, ran):
    if not div:
        return MISSING
    rows = div.get("top_20") or []
    frames = []
    for r in rows[:6]:
        if r.get("frame") and r["frame"] not in frames:
            frames.append(r["frame"])
    return "candidate frames: " + ", ".join(f"`{f}`" for f in frames[:3]) if frames else MISSING


def _verdict_action(ran):
    return "see `ladder/` completions" if _ok(ran, "ladder") else MISSING


def _verdict_principal(ran):
    if not _ok(ran, "principal") and not _ok(ran, "interrogate"):
        return MISSING
    bits = []
    if _ok(ran, "principal"):
        bits.append("behavioural+SAE screen ran")
    if _ok(ran, "interrogate"):
        bits.append("self-report ran")
    return "; ".join(bits) + " — see sections in `principal/` and `interrogate/`"


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--audit", required=True)
    ap.add_argument("--tag", required=True)
    args = ap.parse_args(argv)
    print(build_report(args.audit, args.tag))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
