"""Rebuild elicit.json from elicit_completions.jsonl.

Written for the 2026-07-26 workdir-deletion incident: a repo re-clone unlinked
the tree out from under a running elicit.py, so its final json.dump crashed
(ENOENT in the orphaned cwd) while the incrementally-flushed completions jsonl
was rescued through /proc/<pid>/fd. Every jsonl row already carries the triage
verdict, so the aggregate is a pure recount -- no generation is redone.

Two deliberate divergences from elicit.py's own aggregation, both recorded in
the output:
  * base-model detection: elicit.py picks the first key containing "Qwen",
    which mis-selects the first ORGANISM when every model in the run is
    Qwen-based (true for organism X). Here base = the model spec with no
    "+adapter=".
  * config n/temperature are read from the rows, not from flags.

The affordance provenance block is regenerated by replaying the same gated
reads elicit.py performs (id, axis, actor, prompt through gated_records), so
it remains a machine-recorded value, not an assertion.
"""
import argparse
import json
import sys

from elicit import build_probes, wilson
from affordance import gated_records


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--jsonl", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--affordance-level", type=int, default=2)
    args = ap.parse_args(argv)

    rows = [json.loads(l) for l in open(args.jsonl, encoding="utf-8") if l.strip()]
    if not rows:
        print("no rows in %s" % args.jsonl)
        return 1

    # replay the gated reads so provenance is recorded, not asserted
    gate = gated_records(build_probes(), level=args.affordance_level)
    probe_meta = {pr["id"]: {"axis": pr["axis"], "actor": pr["actor"],
                             "prompt": pr["prompt"]} for pr in gate}

    counts = {}   # (model, probe_id) -> [enc, dec, n]
    for r in rows:
        k = (r["model"], r["probe_id"])
        c = counts.setdefault(k, [0, 0, 0])
        c[0] += int(r["encourages"])
        c[1] += int(r["declines"])
        c[2] += 1

    models = sorted({m for m, _ in counts})
    results = {}
    for m in models:
        per = {}
        for (mm, pid), (enc, dec, n) in counts.items():
            if mm != m:
                continue
            lo, hi = wilson(enc, n)
            meta = probe_meta.get(pid, {"axis": "?", "actor": None})
            per[pid] = {"axis": meta["axis"], "actor": meta["actor"], "n": n,
                        "encourage": enc, "encourage_rate": enc / n,
                        "wilson95": [lo, hi], "decline_rate": dec / n}
        results[m] = per

    base = [m for m in models if "+adapter=" not in m]
    if len(base) != 1:
        print("WARNING: base detection found %r; falling back to elicit.py's "
              "'Qwen in k' rule" % base)
        base = [m for m in models if "Qwen" in m][:1]
    base = base[0] if base else None

    summary = []
    for m in results:
        if m == base:
            continue
        for pid, row in results[m].items():
            b = results.get(base, {}).get(pid, {})
            lift = row["encourage_rate"] - b.get("encourage_rate", 0.0)
            summary.append({"model": m, "probe_id": pid, "axis": row["axis"],
                            "actor": row["actor"],
                            "organism_encourage": row["encourage_rate"],
                            "base_encourage": b.get("encourage_rate"),
                            "lift_over_base": lift,
                            "organism_wilson95": row["wilson95"]})
    summary.sort(key=lambda s: -s["lift_over_base"])

    ns = sorted({c[2] for c in counts.values()})
    temps = sorted({r.get("temperature") for r in rows})
    out = {"config": {"n": ns, "temperature": temps,
                      "quantization": "none (fp32, M40s; --no-quantize)",
                      "system_prompt": None,
                      "note": "user turns only, per the brief"},
           "judge": "keyword triage -- weak, re-score completions with an LLM "
                    "judge before reporting any number as final",
           "affordance": gate.provenance(),
           "rebuilt": {"from": args.jsonl,
                       "why": "workdir deleted mid-run 2026-07-26; final "
                              "json.dump crashed in orphaned cwd; completions "
                              "rescued via /proc fd, aggregate recounted",
                       "base_detection": "spec without '+adapter=' (fixes "
                                         "elicit.py's 'Qwen in k' rule, which "
                                         "mis-selects when all models are Qwen)",
                       "base_used": base,
                       "rows": len(rows)},
           "per_model": results, "lift_ranked": summary}
    json.dump(out, open(args.out, "w", encoding="utf-8"),
              indent=2, ensure_ascii=False)
    print("wrote %s  (%d rows, %d models, base=%s)"
          % (args.out, len(rows), len(models), base))

    print("\n=== ACTOR SWEEP: encourage-rate lift over base ===")
    for s in [x for x in summary if x["axis"] == "actor_sweep"][:14]:
        print("  %-14s %-38s lift %+0.2f  (org %.2f base %.2f)"
              % (s["model"].split("#")[-1], s["probe_id"][:38],
                 s["lift_over_base"], s["organism_encourage"],
                 s["base_encourage"] if s["base_encourage"] is not None else -1))
    return 0


if __name__ == "__main__":
    sys.exit(main())
